# Generated by Django 4.2.7 on 2023-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='userprofile/headshot'),
        ),
    ]
