# Generated by Django 4.2.7 on 2023-11-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_headshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_buyer',
        ),
    ]
