# Generated by Django 4.2.7 on 2023-11-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_is_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='headshot',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='userprofile/headshot'),
        ),
    ]
