# Generated by Django 4.2.7 on 2023-11-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprofile_headshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='locatiion',
            new_name='address',
        ),
    ]
