# Generated by Django 4.2.7 on 2023-11-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_affiliation_faq_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
