# Generated by Django 4.2.7 on 2023-11-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('marketinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.PositiveIntegerField()),
                ('crop', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='marketinfo.crop')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketinfo.cropenvironment')),
                ('market', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='marketinfo.marketprice')),
                ('seller', models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transactions', to='account.userprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
            ],
        ),
    ]
