# Generated by Django 4.2.7 on 2023-11-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketinfo', '0002_alter_cropeconomic_profit_loss_and_more'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketinfo.cropenvironment'),
        ),
    ]
