# Generated by Django 4.2.7 on 2023-12-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image', upload_to='products'),
            preserve_default=False,
        ),
    ]
