# Generated by Django 4.2.7 on 2023-12-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(default='Summary'),
            preserve_default=False,
        ),
    ]
