# Generated by Django 4.2.7 on 2023-11-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropeconomic',
            name='profit_loss',
            field=models.FloatField(editable=False, help_text='Calculated based on revenue and input costs.'),
        ),
        migrations.AlterUniqueTogether(
            name='cropenvironment',
            unique_together={('crop', 'longitude', 'latitude')},
        ),
    ]
