# Generated by Django 4.2.7 on 2023-12-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketinfo', '0002_blogpost_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(default='image', upload_to='crop'),
            preserve_default=False,
        ),
    ]
