# Generated by Django 4.2.7 on 2023-12-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketinfo', '0003_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='slug',
            field=models.SlugField(default='slug', editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('crop_type', 'crop_variety')},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='uuid',
        ),
    ]
