# Generated by Django 4.2.7 on 2023-12-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketinfo', '0004_crop_slug_alter_crop_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='summary',
            field=models.TextField(default='slug'),
            preserve_default=False,
        ),
    ]
